package common

// ChainConstant 定义 Chain 相关的常量
const (
	Parallel            = "parallel"
	Chain               = "chain"
	Route               = "route"
	Body                = "body"
	Flow                = "flow"
	Nodes               = "nodes"
	Node                = "node"
	ID                  = "id"
	Class               = "class"
	File                = "file"
	Name                = "name"
	Enable              = "enable"
	Language            = "language"
	Namespace           = "namespace"
	DefaultNamespace    = "default"
	Value               = "value"
	Any                 = "any"
	Must                = "must"
	Type                = "type"
	Then                = "THEN"
	When                = "WHEN"
	Ser                 = "SER"
	Par                 = "PAR"
	Switch              = "SWITCH"
	Pre                 = "PRE"
	Finally             = "FINALLY"
	If                  = "IF"
	Else                = "ELSE"
	Elif                = "ELIF"
	To                  = "TO"
	Tag                 = "tag"
	IgnoreError         = "ignoreError"
	ThreadPool          = "threadPool"
	While               = "WHILE"
	For                 = "FOR"
	Do                  = "DO"
	Break               = "BREAK"
	Data                = "data"
	Iterator            = "ITERATOR"
	MonitorBus          = "monitorBus"
	CurrChainID         = "currChainId"
	DefaultValue        = "DEFAULT"
	Catch               = "CATCH"
	And                 = "AND"
	Or                  = "OR"
	Not                 = "NOT"
	MaxWaitSeconds      = "maxWaitSeconds"
	MaxWaitMilliseconds = "maxWaitMilliseconds"
	Extends             = "extends"
	Retry               = "retry"
)
